# Generated by Django 4.2.5 on 2023-10-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.IntegerField(primary_key=True, serialize=False, verbose_name='id de usuario')),
                ('rutUsuario', models.CharField(max_length=20, verbose_name='rut de usuario')),
                ('nombreUsuario', models.CharField(max_length=20, verbose_name='nombre de usuario')),
                ('apeUsuario', models.CharField(default='NO VALUE', max_length=20, verbose_name='apellido de usuario')),
                ('pais', models.CharField(default='NO VALUE', max_length=20, verbose_name='pais')),
                ('userNick', models.CharField(default='NO VALUE', max_length=20, verbose_name='nick usuario')),
                ('correo', models.CharField(default='NO VALUE', max_length=20, verbose_name='correo de usuario')),
                ('contraseña', models.CharField(default='NO VALUE', max_length=20, verbose_name='constraseña de usuario')),
            ],
        ),
    ]
