# Generated by Django 4.2.5 on 2023-10-02 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('idHab', models.IntegerField(primary_key=True, serialize=False, verbose_name='id de habitacion')),
                ('tipoHab', models.CharField(max_length=50, verbose_name='tipo de habitacion')),
                ('pisoHab', models.IntegerField(verbose_name='piso de habitacion')),
                ('capacidad', models.CharField(max_length=10, verbose_name='capacidad habitacion')),
                ('comentario', models.CharField(max_length=50, verbose_name='comentario de habitacion')),
                ('precioHab', models.IntegerField(verbose_name='precio de habitacion')),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='userNick',
        ),
    ]
