# Generated by Django 4.2.5 on 2023-10-02 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_habitacion_remove_usuario_usernick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='idUsuario',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id de usuario'),
        ),
    ]
